name: ci

on:
  pull_request:
    types: [opened, reopened]

env:
  AWS_PAGER: ""
  KONNECT_PAT_SECRET_ARN: "arn:aws:secretsmanager:eu-west-1:412431539555:secret:jack/demos/cp-sync-token-vMFbyJ"
  KONG_IMAGE_REPOSITORY: ""
  KONNECT_REGION: "eu"

jobs:
  docker:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          ./run.sh plan
        shell: bash

      - name: PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const fileString = fs.readFileSync('./out.txt')

            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fileString
            })
