name: ci


on:
  pull_request:
    types: [opened, reopened]

env:
  AWS_PAGER: ""
  AWS_REGION: eu-west-1
  KONNECT_PAT_SECRET_ARN: "arn:aws:secretsmanager:eu-west-1:123456789012:secret:jack/demos/cp-sync-token-vMFbyJ"
  KONNECT_REGION: "eu"
  MODE: "plan"

jobs:
  plan:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          ./run.sh plan
        shell: bash

      - name: PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const fileString = fs.readFileSync('./out.txt').toString()
            console.log(fileString)

            github.rest.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fileString
            })
